### ISSUE TITLE
 ChemInf - maintenance chores

### ISSUE THREAD

**Issue by CS76** [Steinbeck-Lab/cheminformatics-python-microservice#162]
- [x] 1) Register functional account - caffeine-devs@uni-jena.de
- [x] 2) Docker Hub / Google artifacts hub account
- [x] 3) Push all public images (cheminformatics-python-microservice, ~~decimer, coconut, rdkit/cdk~~ images) to registry
- [x] 4) Document the details in the docs

**Comment by NishaSharma14** [comment]
Request created for the functional account.

**Comment by NishaSharma14** [comment]
Docker Hub - https://hub.docker.com/r/caffeinejena/cheminformatics-python-microservice

**Comment by NishaSharma14** [comment]
Docs - https://steinbeck-lab.github.io/cheminformatics-python-microservice/docker.html
