### ISSUE TITLE
the production link in the README gives 404

### ISSUE THREAD

**Issue by egonw** [Steinbeck-Lab/cheminformatics-python-microservice#234]
**Describe the bug**
the production link in the README gives 404

**To Reproduce**
1. Go to https://github.com/Steinbeck-Lab/cheminformatics-python-microservice/blob/main/README.md
2. Click on `Production: https://api.naturalproducts.net/latest/docs`
4. See 404 error

**Expected behavior**
A HTTP 200 reply with OpenAPI conten

**Comment by Kohulan** [comment]
@egonw Thanks for the bug report it is now fixed.
