### ISSUE TITLE
Documentation of generate-structures

### ISSUE THREAD

**Issue by JonasSchaub** [Steinbeck-Lab/cheminformatics-python-microservice#246]
Could you add to the documentation of generate-structures which tool is used there? Maygen? surge? Something else?

**Comment by JonasSchaub** [comment]
And do you have any restrictions in place for this and other functions with "high computational demands"? E.g. structure generation scales very unfavorably with the number of atoms given in the molecular formula.

**Comment by Kohulan** [comment]
Limit to 10 heavy atoms or even less? and specify this in the documentation.
