### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by CS76** [Steinbeck-Lab/cheminformatics-python-microservice#25]
Images with a lot of structures will need more time for processing. Increase the time out to allow this and avoid 504 timeout errors. 

Example

![image](https://user-images.githubusercontent.com/4065285/224819835-3760be71-d4b6-40b8-8db9-168299d50593.png)

POST: https://api.naturalproducts.net/chem/process

`{"reference":"chem_instance_11","path":"https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs13321-021-00538-8/MediaObjects/13321_2021_538_Fig9_HTML.png"}`

**Comment by NishaSharma14** [comment]
@CS76 I have added a timeout for 5 minutes now. Can you please check and confirm if this works?
