### ISSUE TITLE
CORS Policy error in convert/mol3D API

### ISSUE THREAD

**Issue by NishaSharma14** [Steinbeck-Lab/cheminformatics-python-microservice#258]
Access to fetch at 'https://dev.api.naturalproducts.net/v1/convert/mol3D?smiles=O%3DC1OC2%3DCC(%3DCC(OC3OC(CO)C(O)C(O)C3O)%3DC2C4%3DC1CCC4)C' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by CS76** [comment]
commit #025d961 fixes this issue
