### ISSUE TITLE
Version number not reflectingin the swagger docs site

### ISSUE THREAD

**Issue by CS76** [Steinbeck-Lab/cheminformatics-python-microservice#281]
**Describe the bug**
Swagger docs don't have the latest version number on the docs page.

<img width="886" alt="image" src="https://github.com/Steinbeck-Lab/cheminformatics-python-microservice/assets/4065285/b24411cb-fde7-4ef5-bec3-6b521790faaa">

https://api.naturalproducts.net/docs

**Expected behavior**
v1.0.0

**Screenshots**
<img width="886" alt="image" src="https://github.com/Steinbeck-Lab/cheminformatics-python-microservice/assets/4065285/718b2c00-a508-445f-8230-4daa6fdce211">

**Desktop (please complete the following information):**

**Comment by NishaSharma14** [comment]
I have also added back the missing build-args in the build workflow.
