### ISSUE TITLE
Better annotations for `toolkit`

### ISSUE THREAD

**Issue by cthoyt** [Steinbeck-Lab/cheminformatics-python-microservice#297]
https://github.com/Steinbeck-Lab/cheminformatics-python-microservice/blob/235ec40a1b5549d39c875019ffad3f962be02b67/app/routers/chem.py#L302

`toolkit: Optional[str] = "cdk"` should not be optional - it's required with a default. It's also better to use `Literal["cdk", "rdkit"]` so FastAPI knows these are the list of allowed values and can do error checking for you. Same idea can be applied in many places

**Comment by cthoyt** [comment]
@CS76 fyi it's very confusing to track how changes are addressed if they are put into an opaque development branch before merging into main

**Comment by CS76** [comment]
@cthoyt Here is the pull request that resolved these issues - https://github.com/Steinbeck-Lab/cheminformatics-python-microservice/pull/307

**Comment by CS76** [comment]
Also, here is a pull requests filter you might find helpful for filtering https://github.com/Steinbeck-Lab/cheminformatics-python-microservice/pulls?q=is%3Apr+base%3Adevelopment
