### ISSUE TITLE
Index endpoints are confusing

### ISSUE THREAD

**Issue by cthoyt** [Steinbeck-Lab/cheminformatics-python-microservice#300]
Each of the components of this service have their own index endpoint like https://dev.api.naturalproducts.net/v1/chem/. This doesn't actually do anything other than return a response code. Since it's not really documented why this is here, I would suggest removing all of these index endpoints, since they are a distraction from the other more important parts

Alternatively, you might have some meta-component that gives information about the service's status/health that is decoupled from the components themselves

**Comment by CS76** [comment]
![image](https://github.com/Steinbeck-Lab/cheminformatics-python-microservice/assets/4065285/fbad4f26-b830-44e7-88d5-27f22d8efcb5)

Health checks are hidden from the schema except for the one at the root (app) level.
