### ISSUE TITLE
Register endpoints into the Bioregistry

### ISSUE THREAD

**Issue by CS76** [Steinbeck-Lab/cheminformatics-python-microservice#331]
For `smiles` and `inchikey` prefixes to make this service more FAIR - particularly finable and accessible.

See this issue template for doing so 
    
https://github.com/biopragmatics/bioregistry/issues/new?labels=Provider%2CNew&projects=&template=new-provider.yml&title=Add+provider+for+%5BX%5D

**Comment by NishaSharma14** [comment]
https://github.com/biopragmatics/bioregistry/issues/931

**Comment by cthoyt** [comment]
Can we make a list of the endpoints that would be worth it? Like descriptors, making an image, anything else? And then we put them for both smiles, inchi, and inchikey (when possible)

**Comment by CS76** [comment]
@cthoyt Sure, we were wondering the same. Will raise more requests soon :)

**Comment by cthoyt** [comment]
You can use a more generic issue template and group it all together, no need to do individual issues for each, since it's clear what's going on here

**Comment by NishaSharma14** [comment]
https://github.com/biopragmatics/bioregistry/pull/932

**Comment by cthoyt** [comment]
Are there any endpoints that work with InChI or InChI keys? or are all endpoints working only for SMILES?

**Comment by CS76** [comment]
Currently, it's either SMILES or MOL block. We will extend support for InChI or InChI keys, and then submit a respective provider request later.

**Comment by cthoyt** [comment]
Great, then I would call this issue done wrt the review :)
