### ISSUE TITLE
Update docs  - Scaling information

### ISSUE THREAD

**Issue by CS76** [Steinbeck-Lab/cheminformatics-python-microservice#332]
Give more insight into scaling - like multiple instances and behind a load balancer. 
Are there recipes to make it easy to spin up your own instance on AWS or Azure?

**Comment by NishaSharma14** [comment]
[screen-capture (6).webm](https://github.com/Steinbeck-Lab/cheminformatics-python-microservice/assets/54287612/4126cb9a-c52c-43a6-b616-08ef48b4920d)



Links - 
**Docker compose** - https://docs.api.naturalproducts.net/docker.html#docker-compose
**GKE** - https://docs.api.naturalproducts.net/cluster-deployment.html#deployment-to-google-kubernetes-engine-gke-using-helm
**Scaling** - https://docs.api.naturalproducts.net/cluster-deployment.html#scaling
