### ISSUE TITLE
Python-like documentation should be removed in favor of the OpenAPI documentation

### ISSUE THREAD

**Issue by CS76** [Steinbeck-Lab/cheminformatics-python-microservice#337]
Documentation of the REST API contains a strange mix of python-like documentation and OpenAPI-actionable documentation. The Python-like documentation should be removed in favor of the OpenAPI documentation.

We need to declare why this is the chosen approach or revert to one style/

**Comment by Kohulan** [comment]
There appear to be ongoing rendering difficulties with FastAPI (https://github.com/tiangolo/fastapi/discussions/9839), particularly in relation to displaying examples and documentation. Sometimes, the documentation may vanish when a user tries to access certain functions. Nevertheless, it would be advantageous to retain both documentation formats, as many users find the Python documentation to be highly understandable and user-friendly.
