### ISSUE TITLE
CI/CD integration

### ISSUE THREAD

**Issue by CS76** [Steinbeck-Lab/cheminformatics-python-microservice#4]

**Comment by NishaSharma14** [comment]
https://dev.api.naturalproducts.net/ is ready and up to date with `development` branch.

https://api.naturalproducts.net/ is up to date with `main` branch.

DEV (dev.api.naturalproducts.net) - Will be updated when the code is merged to development branch & will be deployed by the CRON( 🚋 ) running every 15 min.


PROD (api.naturalproducts.net) - Will be updated when the code is merged to the main branch. But apparently, there is no train for this right now for safety purposes.

For each prod deployment, please reach out to me.


According to good practice deployment to prod, it should only happen when the code is stable and passes all testing in dev.
